/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment;


import Heper.Check;
import Heper.ConnectSQL;
import java.awt.Color;
import java.util.ArrayList;
import java.sql.* ;
import java.util.Collections;
import java.util.Comparator;
import java.util.Random;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QLDSV1 extends javax.swing.JFrame {

    /**
     * Creates new form QLDSV1
     */
    ArrayList<DiemSinhVien> listDiemSV = new ArrayList<>();
    ArrayList<String> listMaSV = new ArrayList<>();
    int Index = 0 ;
    LoginForm st  = new LoginForm();
    
    public QLDSV1() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Quản Lý Điểm Sinh Viên");
        ChayChu();
        DoiMau();
        if( st.CheckDangNhap == true ){
            KetNoi();
        }           
    }
    // Chạy Chũ 
    public void ChayChu(){
        lbTieuDe.setText("  Quản Lý Điểm Sinh Viên");
        Thread st = new Thread(){
            
            public void run(){
                try {
                    while (true) {                        
                         String st = lbTieuDe.getText();
                         char fisrt = st.charAt(0) ;
                         lbTieuDe.setText( st.substring(1, st.length()  ) + fisrt );    
                         Thread.sleep(500);
                    }
                } catch (Exception e) {
                }
            }
        };
        st.start();
    }
    
    // ĐỔ màu cho tiêu đề
    public void DoiMau(){
         Thread st = new Thread(){
             Random rand = new Random();
             @Override
             public void run(){
                 try {
                     while (true) {                         
                         int a = rand.nextInt(255);
                         int b = rand.nextInt(255);
                         int c = rand.nextInt(255);
                         Color color = new Color(a , b ,c);
                         lbTieuDe.setForeground(color) ;
                         Thread.sleep(100);                       
                     }
                 } catch (InterruptedException ex) {
                 }
             }
         };
         st.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTieuDe = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFindMaSV = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbHoTen = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtTiengAnh = new javax.swing.JTextField();
        txtTinHoc = new javax.swing.JTextField();
        txtGiaoDucTC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbDiemTB = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnPre2 = new javax.swing.JButton();
        btnPre1 = new javax.swing.JButton();
        btnNext1 = new javax.swing.JButton();
        btnNext2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbTieuDe.setForeground(java.awt.Color.blue);
        lbTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTieuDe.setText(" Quản Lý Điểm Sinh Viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        jLabel2.setText("Mã SV:");

        btnSearch.setForeground(java.awt.Color.blue);
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFindMaSV, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(btnSearch)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFindMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Họ Tên SV:");

        jLabel4.setText("Mã SV:");

        jLabel5.setText("Tiếng Anh:");

        jLabel6.setText("Tin Học:");

        jLabel7.setText("Giáo Dục TC:");

        lbHoTen.setForeground(java.awt.Color.blue);

        txtMaSV.setForeground(new java.awt.Color(102, 204, 255));

        jLabel8.setText("Điểm TB:");

        lbDiemTB.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lbDiemTB.setForeground(java.awt.Color.blue);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSV)
                    .addComponent(txtTiengAnh)
                    .addComponent(txtTinHoc)
                    .addComponent(txtGiaoDucTC, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaoDucTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );

        jPanel3.setLayout(new java.awt.GridLayout(5, 1, 8, 15));

        btnNew.setForeground(java.awt.Color.blue);
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel3.add(btnNew);

        btnSave.setForeground(java.awt.Color.blue);
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave);

        btnDelete.setForeground(java.awt.Color.blue);
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);

        btnUpdate.setForeground(java.awt.Color.blue);
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate);

        jButton1.setForeground(java.awt.Color.blue);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jPanel4.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        btnPre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/previous.png"))); // NOI18N
        btnPre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPre2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnPre2);

        btnPre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/3695054_music_music player_player_previous_icon.png"))); // NOI18N
        btnPre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPre1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnPre1);

        btnNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/3695045_music_next_next button_player_icon.png"))); // NOI18N
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnNext1);

        btnNext2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/next.png"))); // NOI18N
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });
        jPanel4.add(btnNext2);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ Tên", "Tiếng Anh", "Tin Học", "GDTC", "Điểm TB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel10.setForeground(java.awt.Color.blue);
        jLabel10.setText("3 Sinh viên có điểm cao nhất");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addComponent(lbTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbTieuDe)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Làm mới các textField 
    private void LamTrangTxt(){
        lbHoTen.setText("");
        lbDiemTB.setText("");
        txtTiengAnh.setText("");
        txtGiaoDucTC.setText("");
        txtTinHoc.setText("");
        txtMaSV.setText("");
        txtFindMaSV.setText("");    
    }
    
    // Làm Trắng một vài text Field 
    private void LamTrangTxt2(){
        lbDiemTB.setText("");
        txtTiengAnh.setText("");
        txtGiaoDucTC.setText("");
        txtTinHoc.setText("");
        txtFindMaSV.setText(""); 
    }
    
    // Nút làm trắng các textField
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }   
        LamTrangTxt();
    }//GEN-LAST:event_btnNewActionPerformed

    // Hàm Hiển thị thông tin nên txt
    private void HienThiThongTin( int k ){
        DiemSinhVien sv = listDiemSV.get(k) ;
        lbDiemTB.setText(String.valueOf(sv.getDiemTB()));
        lbHoTen.setText(sv.getHoten());
        txtMaSV.setText(sv.getMaSV());
        txtGiaoDucTC.setText(String.valueOf(sv.getGiaoDuc()));
        txtTiengAnh.setText(String.valueOf(sv.getTiengAnh()));
        txtTinHoc.setText(String.valueOf(sv.getTinHoc()));
    }
    
    private void btnPre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPre2ActionPerformed
         if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }   
         
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }
        Index = 0 ;
        HienThiThongTin(Index);
        if( checkMa() == false ){
            LamTrangTxt2();
        }
    }//GEN-LAST:event_btnPre2ActionPerformed

    
    
    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        } 
        Index = listDiemSV.size() - 1 ;
        HienThiThongTin(Index);
        if( checkMa() == false ){
            LamTrangTxt2();
        }
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void btnPre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPre1ActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }       
        int k = 0 ;
        Index-- ;
        if( Index <= 0 ){
            Index = 0 ;
            k = 1 ;
        }
        HienThiThongTin(Index);
        if( checkMa() == false ){
            LamTrangTxt2();
        }
        if( k==1 ) JOptionPane.showMessageDialog(rootPane, "bạn đang ở đầu danh sách");
    }//GEN-LAST:event_btnPre1ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }    
        int k = 0 ;
        Index++ ;
        if( Index  >= listDiemSV.size() - 1 ){
            Index = listDiemSV.size() -1 ;
            k = 1 ;
        }
        HienThiThongTin(Index);
        if( checkMa() == false ){
            LamTrangTxt2();
        }
        if( k == 1 ) JOptionPane.showMessageDialog(rootPane, "bạn đang ở cuối danh sách");
    }//GEN-LAST:event_btnNext1ActionPerformed
    
    // Check mã xem có ở trong Bảng điểm k
    private boolean checkMa(){
        try {
            try (  Connection con = ConnectSQL.OpenLink() ;
                   Statement stmt = con.createStatement();
                    ){
                   String sql = "select MaSV from GRADE" ;
                   ResultSet rs = stmt.executeQuery(sql);
                   
                   while ( rs.next() ) {                    
                       if( rs.getString("MaSV").equalsIgnoreCase(txtMaSV.getText())){
                            return true ;
                       }
                }
            }
        } catch (Exception e) {
        }
        return false ;
    }
    
    // thêm mã sv từ bang sinh viên vào list
    private void ListSV(){
        try {
            String sql = "select MaSV from STUDENTS";
            try(   Connection con = ConnectSQL.OpenLink();
                   Statement stmt = con.createStatement();
                    ){
                   ResultSet rs = stmt.executeQuery(sql);
                   
                   while( rs.next() ){
                       listMaSV.add(rs.getString("MaSV"));
                   }
            }
        } catch (Exception e) {
        }
    }
    
    // Check Ma có ở trong bảng sinh viên k
    private boolean CheckMaTrung(){
        ListSV();
        for( int i=0 ; i<listMaSV.size() ; i++ ){
            if( listMaSV.get(i).equalsIgnoreCase(txtMaSV.getText())){
                return true ;
            }
        }
        return false ;
    }
    
    // Save file
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }   
        
        if( txtGiaoDucTC.getText().isEmpty() || txtTiengAnh.getText().isEmpty() || txtMaSV.getText().isEmpty() 
                 || txtTinHoc.getText().isEmpty() ){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin vào các ô trống");
            return ;
        }
        
        if( Check.CheckMa(txtMaSV.getText())== false ){
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đúng định dạng");
            return ;
        }
        
        if( Check.CheckDoDaiMa(txtMaSV.getText()) == false ){
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu Mã SV > 7 ký tự");
            return ;
        }
        
        if( checkMa() == true ){
            JOptionPane.showMessageDialog(rootPane, "Mã đã được nhập điểm rồi");
            return;
        }
        
        if( CheckMaTrung() == false ){
            JOptionPane.showMessageDialog(rootPane, "Mã SV không tồn tại trong danh sách Sinh Viên");
            return ; 
        }
        
        if( Check.CheckDiem( txtTiengAnh.getText()) == false || Check.CheckDiem( txtGiaoDucTC.getText()) == false || Check.CheckDiem( txtTinHoc.getText()) == false ){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập điểm trong khoảng 1 -> 10");
            return ;            
        }        
        
        try {
            String sql = "insert GRADE values ( ? , ? , ? , ? , ? )" ;
            try(   Connection con = ConnectSQL.OpenLink();
                   PreparedStatement pstmt = con.prepareCall(sql);
                   ){
                   pstmt.setInt( 1, Integer.parseInt(txtMaSV.getText().substring(2))  );
                   pstmt.setString(2, txtMaSV.getText());
                   pstmt.setDouble( 3, Double.valueOf(txtTiengAnh.getText()) );
                   pstmt.setDouble( 4, Double.valueOf(txtTinHoc.getText()) );
                   pstmt.setDouble( 5, Double.valueOf(txtGiaoDucTC.getText()) );
                   
                   pstmt.executeUpdate();
                   JOptionPane.showMessageDialog(rootPane, "Bạn Đã Thêm Thành Công");
            }
        } catch (Exception e) {
        }
        KetNoi();
    }//GEN-LAST:event_btnSaveActionPerformed

    // Delete
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }   
        
        int chose = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa không?", "Xác Nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if( chose == JOptionPane.NO_OPTION ){
           return ;
        }
        
        try {
            String sql =  "delete from GRADE where MaSV = ?" ;
            try(   Connection con = ConnectSQL.OpenLink();
                   PreparedStatement pstmt = con.prepareCall(sql);
               ){
                   pstmt.setString(1, txtMaSV.getText());
                   pstmt.executeUpdate();
                   LamTrangTxt();
                   JOptionPane.showMessageDialog(rootPane , "Bạn Xóa Thành Công");
                }
        } catch (Exception e) {
        }
        KetNoi();
    }//GEN-LAST:event_btnDeleteActionPerformed

    // Update
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }   
        
        if( txtGiaoDucTC.getText().isEmpty() || txtTiengAnh.getText().isEmpty() || txtMaSV.getText().isEmpty() 
                 || txtTinHoc.getText().isEmpty() ){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin vào các ô trống");
            return ;
        }        
        
        if( checkMa() == false ){
            JOptionPane.showMessageDialog(rootPane, "Yêu Cầu Mã Sinh Viên phải trùng với data");
            return ;
        }
        
        try {
            String sql = "Update GRADE set TiengAnh = ? , TinHoc = ?, GDTC = ? where MaSV = ?";
            try(   Connection con = ConnectSQL.OpenLink();
                   PreparedStatement pstmt = con.prepareCall(sql);
                    ){
                  pstmt.setDouble(1,Double.valueOf(txtTiengAnh.getText()) );
                  pstmt.setDouble(2,Double.valueOf(txtTinHoc.getText()) );
                  pstmt.setDouble(3,Double.valueOf(txtGiaoDucTC.getText()) );
                  pstmt.setString(4, txtMaSV.getText());
                  pstmt.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane, "Bạn Update thành công");
            }   
        } catch (Exception e) {
        }
        KetNoi();       
    }//GEN-LAST:event_btnUpdateActionPerformed

    // Tìm kiếm
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }   
        boolean sk  = true ; 
        
        for( int i=0 ; i<listDiemSV.size() ; i++ ){
            DiemSinhVien sv = listDiemSV.get(i);
            if( txtFindMaSV.getText().equalsIgnoreCase(sv.getMaSV())){
                 HienThiThongTin(i);
                 Index = i ;
                 sk = false;
                 break; 
            }
        }
        
        if( sk == true )  JOptionPane.showMessageDialog(rootPane, "Mã SV bạn tìm không tồn tại");
    }//GEN-LAST:event_btnSearchActionPerformed

    // Kích vào table và hiển thị nên txt
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
         Index = table.getSelectedRow();
         HienThiThongTin(Index);
    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }  
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Kết nối nối SQL
    private void KetNoi(){
         try {
             String sql = "select HoTen, STUDENTS.MaSV , TiengAnh , TinHoc , GDTC " +
                          "from GRADE right outer join STUDENTS on GRADE.MaSV = STUDENTS.MaSV";
             try (   Connection con = ConnectSQL.OpenLink();
                     Statement pstmt = con.createStatement();
                     ){
                     ResultSet rs = pstmt.executeQuery(sql);
                     listDiemSV.clear();
                     while( rs.next() ){
                          DiemSinhVien sv = new DiemSinhVien();
                          sv.setMaSV(rs.getString("MaSV"));
                          sv.setHoten(rs.getString("HoTen"));
                          sv.setTiengAnh(rs.getDouble("TiengAnh"));
                          sv.setTinHoc(rs.getDouble("TinHoc"));
                          sv.setGiaoDuc(rs.getDouble("GDTC"));
                          listDiemSV.add(sv);
                     }
             }
             DoVaoBang();
        } catch (Exception e) {
        }
    }
    
    // Thêm vào bảng và sắp xếp
    private void DoVaoBang(){
         int k ;
         DefaultTableModel model = (DefaultTableModel) table.getModel() ;
         model.setRowCount(0);
         
         listDiemSV.sort( (a , b) -> {
            return Double.compare( b.getDiemTB(), a.getDiemTB() );
         });
         
         if( listDiemSV.size() < 3 ){
             k = listDiemSV.size();
         }else{
             k = 3 ;
         }
         
         for( int i=0 ; i<k ; i++  ){
             DiemSinhVien x = listDiemSV.get(i);
             model.addRow( new Object[] { x.getMaSV() , x.getHoten() , x.getTiengAnh() , x.getTinHoc() , x.getGiaoDuc() , x.getDiemTB()});
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDSV1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnNext2;
    private javax.swing.JButton btnPre1;
    private javax.swing.JButton btnPre2;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDiemTB;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbTieuDe;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtFindMaSV;
    private javax.swing.JTextField txtGiaoDucTC;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTiengAnh;
    private javax.swing.JTextField txtTinHoc;
    // End of variables declaration//GEN-END:variables
}
