/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment;

import Heper.Check;
import Heper.ConnectSQL;
import java.awt.Color;
import java.awt.Image;
import java.awt.JobAttributes;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QLSV extends javax.swing.JFrame {

    /**
     * Creates new form QLSV
     */
    DefaultTableModel table_model ;
    int Index ;
    File source  ; 
    File destImage ;
    String nameImage = null ;
    boolean CheckImg  ;
    LoginForm st  ;
    public QLSV() {
        initComponents();
        setTitle("Quản Lý Sinh Viên");
        setResizable(false);
        setLocationRelativeTo(null);
        table_model = (DefaultTableModel) table.getModel();
        CheckImg = false;
        DoiMau();
        ChayChu();
        if( st.CheckDangNhap == true ){
            KetNoi();
        }          
    }

    // Hàm Chạy Chữ
    public void ChayChu(){
        lbTieuDe.setText(" Quản Lý Sinh Viên");
        Thread st = new Thread(){
            
            public void run(){
                try {
                    while (true) {                        
                         String st = lbTieuDe.getText();
                         char fisrt = st.charAt(0) ;
                         lbTieuDe.setText( st.substring(1, st.length()  ) + fisrt );    
                         Thread.sleep(500);
                    }
                } catch (Exception e) {
                }
            }
        };
        st.start();
    }
    
    // Hàm Đổ Màu Cho Chữ
    public void DoiMau(){
         Thread st = new Thread(){
             Random rand = new Random();
             @Override
             public void run(){
                 try {
                     while (true) {                         
                         int a = rand.nextInt(255);
                         int b = rand.nextInt(255);
                         int c = rand.nextInt(255);
                         Color color = new Color(a , b ,c);
                         lbTieuDe.setForeground(color) ;
                         Thread.sleep(100);                       
                     }
                 } catch (InterruptedException ex) {
                 }
             }
         };
         st.start();
    }
    
    // Kết nối Với SQL
    private void KetNoi(){
        try {
            try(   Connection con = ConnectSQL.OpenLink();
                   Statement stmt = con.createStatement();
                    ){
                   String sql = "select * from STUDENTS";
                   ResultSet rs = stmt.executeQuery(sql);
                  
                   table_model.setRowCount(0);
                   while( rs.next() ){
                       Vector vs = new Vector();
                       vs.add(rs.getString("MaSV"));
                       vs.add(rs.getString("HoTen"));
                       vs.add(rs.getString("Email"));
                       vs.add(rs.getString("SoDT"));
                       vs.add(rs.getInt("GioiTinh") == 1 ? "Nam" : "Nữ" );
                       vs.add(rs.getString("DiaChi"));
                       vs.add(rs.getString("Hinh"));
                       table_model.addRow(vs);
                   }
            }
        } catch (Exception e) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbTieuDe = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        CheckNam = new javax.swing.JCheckBox();
        CheckNu = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lbAnh = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTieuDe.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbTieuDe.setForeground(java.awt.Color.black);
        lbTieuDe.setText("Quản Lý Sinh Viên");

        jLabel2.setText("Mã SV:");

        jLabel3.setText("Họ Tên:");

        jLabel4.setText("Số ĐT:");

        jLabel5.setText("Giới Tính:");

        jLabel6.setText("Email:");

        buttonGroup1.add(CheckNam);
        CheckNam.setSelected(true);
        CheckNam.setText("Nam");

        buttonGroup1.add(CheckNu);
        CheckNu.setText("Nữ");

        jLabel7.setText("Địa Chỉ:");

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAnhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 14, 20));

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Add.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel2.add(btnNew);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search.png"))); // NOI18N
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel2.add(btnFind);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logout.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ Tên", "Email", "Số ĐT", "Giới Tính", "Địa Chỉ", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSV)
                            .addComponent(txtHoTen)
                            .addComponent(txtEmail)
                            .addComponent(txtSoDT, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(CheckNam, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(CheckNu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbTieuDe)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CheckNam)
                            .addComponent(CheckNu))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // hàm hiển thị nên cách textField 
    private void HienThiNguocLai( int k ){
         txtMaSV.setText( table.getValueAt(k, 0).toString() );
         txtHoTen.setText( table.getValueAt(k, 1).toString() );
         txtEmail.setText( table.getValueAt(k, 2).toString() );
         txtSoDT.setText( table.getValueAt(k, 3).toString() );
         if( table.getValueAt(k, 4).toString().equalsIgnoreCase("Nam")){
             CheckNam.setSelected(true);
         }else{
             CheckNu.setSelected(true);
         }
         txtDiaChi.setText( table.getValueAt(k, 5).toString() );           
         ImageIcon icon = new ImageIcon("img/"+ table.getValueAt(k, 6).toString() + ".jpg" );
         lbAnh.setIcon(icon);
                
    }
    
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        Index = table.getSelectedRow();
        HienThiNguocLai(Index);
    }//GEN-LAST:event_tableMouseClicked

    // Hàm làm trắng các textField
    private void LamTrangTxt(){
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtHoTen.setText("");
        txtMaSV.setText("");
        txtSoDT.setText("");
        CheckNam.setSelected(true);
        lbAnh.setIcon(null);   
        CheckImg = false ;
    }
    
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }        
          LamTrangTxt();
    }//GEN-LAST:event_btnNewActionPerformed

    // Check mã MaSV có trùng không
    private boolean CheckMa(){
        for( int i=0 ; i<table_model.getRowCount() ; i++ ){
             if( txtMaSV.getText().equalsIgnoreCase(table.getValueAt(i, 0).toString() ) ){
                 return true ;
             }
        }
        return false ;
    }
    
    // nút lưu sinh vào data
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }  
        
        try {
            if( txtDiaChi.getText().isEmpty() || txtEmail.getText().isEmpty() || txtHoTen.getText().isEmpty() 
                    || txtMaSV.getText().isEmpty() || txtSoDT.getText().isEmpty() ){
                 JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin");
                 return ;
            }
            
            if( CheckMa() == true ){
                JOptionPane.showMessageDialog(rootPane, "Mã SV trùng rồi");
                return ;
            }
            
            if( Check.CheckDoDaiMa(txtMaSV.getText()) == false ){
                JOptionPane.showMessageDialog(rootPane, "Mã SV phải lớn hơn 7 ký tự");
                return ;
            }
            
            if( Check.CheckMa(txtMaSV.getText()) == false ){
                JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đúng định dạng");
                return ;
            }
           
            if( Check.CheckTen(txtHoTen.getText()) == false ){
                JOptionPane.showMessageDialog(rootPane, "Họ Tên sai");
                return ;               
            }            
            
            if( Check.CheckEmail(txtEmail.getText()) == false ){
                JOptionPane.showMessageDialog(rootPane, "Email sai");
                return ;               
            }                
            
            if( Check.CheckSDT(txtSoDT.getText()) == false ){
                JOptionPane.showMessageDialog(rootPane, "SĐT sai");
                return ;
            }
            
            String sql = "insert STUDENTS values ( ? , ? , ? ,? , ? , ? , ?)";
            try (  Connection con = ConnectSQL.OpenLink();
                   PreparedStatement pstmt = con.prepareCall(sql);
                    ){
                   pstmt.setString( 1, txtMaSV.getText());
                   pstmt.setString( 2, txtHoTen.getText());
                   pstmt.setString( 3, txtEmail.getText());
                   pstmt.setString( 4, txtSoDT.getText());
                   pstmt.setInt( 5, CheckNam.isSelected() ? 1 : 0);
                   pstmt.setString( 6 , txtDiaChi.getText());  
                   if( CheckImg == true ){
                       CopyImg();             
                   }else{
                       nameImage = "Unknown" ;
                       CheckImg = false ;
                   }
                   pstmt.setString( 7, nameImage);  
                   pstmt.executeUpdate();
                   JOptionPane.showMessageDialog(rootPane, "Bạn đã thêm thành công");
            }
            KetNoi();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    // Xóa 
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }  
        
        int chose = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa k?", "Comfirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if( chose == JOptionPane.NO_OPTION ){
           return ;
        }
        
        Index = table.getSelectedRow();
        if( Index == -1 ){
             JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn dòng bạn muốn xóa");
             return ;
        }
        
        try {
            String sql = "delete from STUDENTS where MaSV = ? " + 
                         "delete from GRADE where MaSV = ?"  ;
            try(   Connection con = ConnectSQL.OpenLink();
                   PreparedStatement pstmt = con.prepareCall(sql);
               ){
                   pstmt.setString(1, table.getValueAt( Index, 0).toString() );
                   pstmt.setString(2, table.getValueAt( Index, 0).toString() );
                   pstmt.executeUpdate();
                   JOptionPane.showMessageDialog(rootPane , "Bạn Xóa Thành Công");
                }
        } catch (Exception e) {
        }
        KetNoi();
    }//GEN-LAST:event_btnDeleteActionPerformed

    // Cập Nhập Sinh Viên 
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }  
        
        Index = table.getSelectedRow();        
        if( Index == -1 ){
             JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn dòng bạn muốn cập nhập");
             return ;
        }
        
        if (Check.CheckDoDaiMa(txtMaSV.getText()) == false) {
            JOptionPane.showMessageDialog(rootPane, "Mã SV phải lớn hơn 7 ký tự");
            return;
        }

        if (Check.CheckMa(txtMaSV.getText()) == false) {
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đúng định dạng");
            return;
        }

        if (Check.CheckTen(txtHoTen.getText()) == false) {
            JOptionPane.showMessageDialog(rootPane, "Họ Tên sai");
            return;
        }

        if (Check.CheckEmail(txtEmail.getText()) == false) {
            JOptionPane.showMessageDialog(rootPane, "Email sai");
            return;
        }

        if (Check.CheckSDT(txtSoDT.getText()) == false) {
            JOptionPane.showMessageDialog(rootPane, "SĐT sai");
            return;
        }
        
        try {
            String sql = "Update STUDENTS set HoTen = ? , Email =? , SoDT = ?, GioiTinh = ? , DiaChi = ?, Hinh = ? where MaSV = ?"  ;
            try(  Connection con = ConnectSQL.OpenLink();
                  PreparedStatement pstmt = con.prepareCall(sql);
                   ){
                  pstmt.setString(1, txtHoTen.getText());
                  pstmt.setString(2, txtEmail.getText());
                  pstmt.setString(3, txtSoDT.getText());
                  pstmt.setInt(4, CheckNam.isSelected() ? 1 : 0 );
                  pstmt.setString(5, txtDiaChi.getText()); 
                  
                  if( CheckImg == true ){
//                       File file = new File("img/" + txtMaSV.getText() + ".jpg");
//                       file.delete();
                       CopyImg();
                       int sk = nameImage.lastIndexOf('.');
                       nameImage = nameImage.substring(0, sk);                       
                  }else{
                       nameImage = txtMaSV.getText();
                       CheckImg = false ;
                  }
                  pstmt.setString(6,  nameImage);
                  pstmt.setString(7, txtMaSV.getText());
                  pstmt.executeUpdate();
                  JOptionPane.showMessageDialog(rootPane, "Cập Nhập Thành Công");
            }
        } catch (Exception e) {
        }
        KetNoi();
    }//GEN-LAST:event_btnUpdateActionPerformed
    
    // Thêm ảnh từ file choser
    private void lbAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAnhMouseClicked
       // Click vào lbl ảnh để show ảnh ra lbl
        try {
            JFileChooser jfc = new JFileChooser();
            int result = jfc.showOpenDialog(null);
            if (result == JFileChooser.APPROVE_OPTION) {
                source = jfc.getSelectedFile();
                lbAnh.setIcon(new ImageIcon(source.getAbsolutePath()));
                CheckImg = true ;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_lbAnhMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }   
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        if( st.CheckDangNhap == false ){
            JOptionPane.showMessageDialog(rootPane, "Mời đăng nhập");
            return;
        }  
        
        String input = JOptionPane.showInputDialog(rootPane, "Vui lòng nhập Mã bạn muốn tìm");
        boolean checkInput = false ;
        
        if( input == null ){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã bạn muốn tìm");
            return  ;
        }
            
        for( int i=0 ; i<table.getRowCount() ; i++ ){
            if( table.getValueAt(i, 0).toString().equalsIgnoreCase(input) ){
                HienThiNguocLai(i);
                checkInput = true ;
                break ;
            }
        }
        if( checkInput == false ) JOptionPane.showMessageDialog(rootPane, "Mã SV bạn cần tìm không có");
    }//GEN-LAST:event_btnFindActionPerformed

    private void CopyImg(){
       try {
            String name = txtMaSV.getText() ;
            File file = new File("img/" + txtMaSV.getText() + ".jpg");
            if( file.exists() ){
               file.delete();            
            }
              
            destImage = new File("img/" + name + ".jpg");
//          fullpath = file.getAbsolutePath();
            nameImage = destImage.getName();
       
//          link gốc, link đích đến, tên ảnh sau khi sao chép
            InputStream is = null;
            OutputStream os = null;
            try {
                is = new FileInputStream(source);
                os = new FileOutputStream(destImage);
                byte[] buffer = new byte[1024 * 2];
                int length;
                while ((length = is.read(buffer)) > 0) {
                    os.write(buffer, 0, length);
                }
            } finally {
                if (is != null) {
                    is.close();
                }
                if (os != null) {
                    os.close();
                }
            }
            //  link gốc, link đích đến, tên ảnh sau khi sao chép
        } catch (Exception e) {
            e.printStackTrace();
        }    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckNam;
    private javax.swing.JCheckBox CheckNu;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbAnh;
    private javax.swing.JLabel lbTieuDe;
    private javax.swing.JTable table;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtSoDT;
    // End of variables declaration//GEN-END:variables

    private String randomString(Random random, int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
