/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package slide4_demo;

/**
 *
 * @author ASUS
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        mnFile_new = new javax.swing.JMenuItem();
        mnuFile_open = new javax.swing.JMenuItem();
        mnuFile_save = new javax.swing.JMenuItem();
        mnuFile_exit = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu7.setText("File");

        mnFile_new.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnFile_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/f79d76f26e3ab3da1825a06c0ab46855.png"))); // NOI18N
        mnFile_new.setText("New");
        mnFile_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFile_newActionPerformed(evt);
            }
        });
        jMenu7.add(mnFile_new);

        mnuFile_open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Open folder.png"))); // NOI18N
        mnuFile_open.setText("Open");
        jMenu7.add(mnuFile_open);

        mnuFile_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Save.png"))); // NOI18N
        mnuFile_save.setText("Save");
        mnuFile_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFile_saveActionPerformed(evt);
            }
        });
        jMenu7.add(mnuFile_save);

        mnuFile_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Exit.png"))); // NOI18N
        mnuFile_exit.setText("Exit");
        mnuFile_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFile_exitActionPerformed(evt);
            }
        });
        jMenu7.add(mnuFile_exit);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuFile_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFile_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuFile_saveActionPerformed

    private void mnFile_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFile_newActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnFile_newActionPerformed

    private void mnuFile_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFile_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuFile_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnFile_new;
    private javax.swing.JMenuItem mnuFile_exit;
    private javax.swing.JMenuItem mnuFile_open;
    private javax.swing.JMenuItem mnuFile_save;
    // End of variables declaration//GEN-END:variables
}
