/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai2;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    NewJFrame nv ;
    public NewJFrame1() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);   
        nv  = new NewJFrame(); 
        DoVaoCBB();
        HienThiNenTxt();
    }

    private void DoVaoCBB(){
        try {
            try (   Connection con = ConnectSQL.OpenLink();
                    Statement stmt = con.createStatement();
                    ){
                   String sql = "select MaMH from MONHOC ";
                   ResultSet rs = stmt.executeQuery(sql);
                   
                   while ( rs.next() ) {                    
                       cbbMaMon.addItem(rs.getString(1));
                }
            } 
        } catch (Exception e) {
        }
    }
    
    private void HienThiNenTxt(){
        try {
            String sql = "select TenMH , diem from MONHOC join DIEM on DIEM.MaMH = MONHOC.MaMH where Masv = ? and DIEM.MaMH = ? ";
            try (   Connection con = ConnectSQL.OpenLink();
                    PreparedStatement stmt = con.prepareStatement(sql);
                    ){                 
                   stmt.setString(1, nv.MaSV);
                   stmt.setString(2, nv.MaMH);
                   ResultSet rs = stmt.executeQuery();
                   txtMaSV.setText(nv.MaSV);
                   cbbMaMon.setSelectedItem(nv.MaMH);                   
                   while ( rs.next() ) {                    
                       txtTenMon.setText(rs.getString(1));
                       txtDiem.setText(String.valueOf(rs.getFloat(2)));
                }
            } 
        } catch (Exception e) {
        }   
    }
    
    private void ClearTxt(){
        txtDiem.setText("");
        txtMaSV.setText("");
        txtTenMon.setText("");
        cbbMaMon.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        txtTenMon = new javax.swing.JTextField();
        cbbMaMon = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("THÔNG TIN SINH VIÊN");

        jLabel2.setText("Mã SV");

        jLabel3.setText("Tên Môn");

        jLabel4.setText("Mã Môn");

        jLabel5.setText("Điểm");

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMaMon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenMon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton3))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClearTxt();
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean CheckTrung(){
        try {
            try (   Connection con = ConnectSQL.OpenLink();
                    Statement stmt = con.createStatement();
                    ){
                    String sql = "select * from DIEM ";
                    ResultSet rs = stmt.executeQuery(sql);
                    
                    while ( rs.next() ) {                    
                         if( txtMaSV.getText().equalsIgnoreCase(rs.getString(1)) && cbbMaMon.getSelectedItem().toString().equalsIgnoreCase(rs.getString(2)))
                               return true ;
                }
                
            } 
        } catch (Exception e) {
        }
        return false ;
    }
    
    private boolean CheckDiem(){
        try {
            Double db = Double.valueOf(txtDiem.getText()) ;
            if( db >=0 && db <= 10 ) 
                return true ;
        } catch (Exception e) {
            return false;
        }
        return false ;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if( CheckTrung() == true ){
            JOptionPane.showMessageDialog(rootPane, "ma trung roi");
            return ;
        }
        
        if( CheckDiem() == false ){
            JOptionPane.showMessageDialog(rootPane, "Diem Sai dinh dang");
            return ;
        }
        
        try {
            String sql = "insert DIEM values ( ? , ? , ? )";
            try (   Connection con = ConnectSQL.OpenLink();
                    PreparedStatement stmt = con.prepareStatement(sql);
                    ){                 
                    stmt.setString(1, txtMaSV.getText());
                    stmt.setString(2, cbbMaMon.getSelectedItem().toString() );
                    stmt.setFloat(3, Float.valueOf(txtDiem.getText()));
                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Insert is successfully");
            } 
        } catch (Exception e) {
        }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if( CheckTrung() == false ){
            JOptionPane.showMessageDialog(rootPane, "ma trung roi");
            return ;
        }
        
        if( CheckDiem() == false ){
            JOptionPane.showMessageDialog(rootPane, "Diem Sai dinh dang");
            return ;
        }      
        try {
            String sql = "Update DIEM set diem = ? where Masv = ? and MaMH = ? ";
            try (   Connection con = ConnectSQL.OpenLink();
                    PreparedStatement stmt = con.prepareStatement(sql);
                    ){                 
                    stmt.setString(2, txtMaSV.getText());
                    stmt.setString(3, cbbMaMon.getSelectedItem().toString() );
                    stmt.setFloat(1, Float.valueOf(txtDiem.getText()));
                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Update is successfully");
            } 
        } catch (Exception e) {
        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbMaMon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
}
