/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baiontap2;
import java.sql.* ;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    DefaultComboBoxModel model_cbb ;
    NewJFrame vc = new NewJFrame();
    public NewJFrame1() {
        initComponents();
        setTitle("Quản lý học sinh");
        setResizable(false);
        setLocationRelativeTo(null);
        
        model_cbb = (DefaultComboBoxModel) cbbMaMon.getModel();
        DoVaoCBB();
        HienThi();
    }

    private void DoVaoCBB () {
        try {
            try (  Connection con = ConnectSQL.OpenLinkSQL();
                   Statement stmt = con.createStatement();
                    ) {
                  String sql = "select MaMH from MONHOC" ;
                  ResultSet rs = stmt.executeQuery(sql);
                  
                  while (rs.next()) {                    
                    model_cbb.addElement(rs.getString("MaMH"));
                }
                
            } 
        } catch (Exception e) {
        }
    }
    
    private void HienThi(){
         try {
             String sql = "select TenMH , diem from MONHOC join DIEM on MONHOC.MaMH = DIEM.MaMH where DIEM.MaMH = ? and Masv = ? ";
             try (   Connection con = ConnectSQL.OpenLinkSQL();
                     PreparedStatement stmt = con.prepareStatement(sql);
                     ){ 
                     stmt.setString(1, vc.maMH );
                     stmt.setString(2, vc.maSS);
                     ResultSet rs = stmt.executeQuery();
                     
                     txtMaSV.setText(vc.maSS);
                     cbbMaMon.setSelectedItem(vc.maMH);
                     while (rs.next() ) {                     
                        txtTenMon.setText(rs.getString("TenMH"));
                        txtDiem.setText( String.valueOf(rs.getString("diem")));                     
                  }

                                      
             } catch (Exception e) {
             }
        } catch (Exception e) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtMaSV = new javax.swing.JTextField();
        cbbMaMon = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenMon = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã SV:");

        jLabel2.setText("Điểm: ");

        jLabel3.setText("Mã Môn:");

        jLabel4.setText("Họ Tên: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaSV)
                            .addComponent(cbbMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenMon, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(cbbMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel4)
                    .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtDiem.setText("");
        txtMaSV.setText("");
        txtTenMon.setText("");
        DoVaoCBB();
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean CheckMa(){
        try {
            String sql = "select MaMH from DIEM where Masv = ? and MaMH = ? " ;
            try (  Connection con = ConnectSQL.OpenLinkSQL();
                   PreparedStatement stmt = con.prepareCall(sql);
                    ) {
                  stmt.setString(1, txtMaSV.getText());
                  stmt.setString(2, cbbMaMon.getSelectedItem().toString());
                  ResultSet rs = stmt.executeQuery();
                  
                  while ( rs.next() ) {                    
                     if( rs.getString("MaMH").equalsIgnoreCase(cbbMaMon.getSelectedItem().toString())){
                         return true ;
                     }
                }
            } 
        } catch (Exception e) {
        }
        return false ;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if( CheckMa() == true ){
            JOptionPane.showMessageDialog(rootPane, "Ma trung roi");
            return;
        }
        
        try {
            double a = Double.valueOf(txtDiem.getText());
            if( a < 0 || a > 10 ){
                JOptionPane.showMessageDialog(rootPane, "Khoang diem tu 0 -> 10");
                return ;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Khong dc nhap chu");
            return ;
        }
        
        try {
            String sql = "Insert DIEM values ( ? , ? , ? )";
            try (   Connection con = ConnectSQL.OpenLinkSQL();
                    PreparedStatement stmt = con.prepareCall(sql);
                    ){
                    stmt.setString(1,  txtMaSV.getText());
                    stmt.setString(2,  cbbMaMon.getSelectedItem().toString() );
                    stmt.setFloat(3,  Float.valueOf(txtDiem.getText()));
                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Insert is seccessfull");
                    
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String sql = "Update DIEM set diem = ? where Masv = ? and MaMH = ? ";
            try (   Connection con = ConnectSQL.OpenLinkSQL();
                    PreparedStatement stmt = con.prepareCall(sql);
                    ){
                    stmt.setString(2,  txtMaSV.getText());
                    stmt.setString(3,  cbbMaMon.getSelectedItem().toString() );
                    stmt.setFloat(1,  Float.valueOf(txtDiem.getText()));
                    stmt.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Update is seccessfull");
                    
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbMaMon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
}
